services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=odoo14
      - POSTGRES_PASSWORD=odoo14
    volumes:
      - postgres-data:/var/lib/postgresql/data # Datos persistentes de Postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "odoo14"]
      interval: 10s
      retries: 5

  odoo:
    image: odoo:14.0
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${ODOO_PORT:-8069}:${ODOO_PORT:-8069}"
    volumes:
      - ./addons:/mnt/extra-addons  # Monta la carpeta local 'addons'
      - ./odoo.conf:/etc/odoo/odoo.conf  # Permite modificar la configuración
      - odoo-data:/var/lib/odoo  # Datos persistentes de Odoo
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: dayronpeeta@gmail.com  
      PGADMIN_DEFAULT_PASSWORD: postgres  
    ports:
      - "8080:80"  # Puerto para acceder a pgAdmin
    depends_on:
      - postgres

volumes:
  postgres-data:
  odoo-data: